version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: microservices_backend
    ports:
      - "8000:8000"  # Lumen API
      - "3001:3001"  # Node.js API
    volumes:
      - ./backend/lumen:/app/backend-lumen
      - ./backend/node:/app/backend-node
    depends_on:
      - mysql_db
      - redis_cache
    environment:
      # Lumen environment variables
      - APP_NAME=LumenMicroservice
      - APP_ENV=local
      - APP_KEY=base64:sPqM8kkhL+HJEj1P9nYPOQO2VPxVy+Rw+hdVTEX1M5Y=
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - APP_TIMEZONE=UTC
      - DB_CONNECTION=mysql
      - DB_HOST=mysql_db
      - DB_PORT=3306
      - DB_DATABASE=microservices
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - CACHE_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - REDIS_HOST=redis_cache
      - REDIS_PORT=6379
      - JWT_SECRET=9Zn5GgWDEwJBhnrMmFxBJHudKbP4vNYc
      - JWT_TTL=60
      - JWT_REFRESH_TTL=20160
      # Node.js environment variables
      - NODE_ENV=development
      # Redis configuration
      - REDIS_HOST=redis_cache
      - REDIS_PORT=6379
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_api
    ports:
      - "80:80"
    volumes:
      - ./backend/lumen:/var/www/backend
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
    networks:
      - app-network

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: microservices
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-network

  redis_cache:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  mysql_data:
  redis_data:

networks:
  app-network:
    driver: bridge
