name: Lumen Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/lumen/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/lumen/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql, zip
        coverage: xdebug

    - name: Copy .env
      run: cp backend/lumen/.env.example backend/lumen/.env

    - name: Install Dependencies
      working-directory: backend/lumen
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      working-directory: backend/lumen
      run: php artisan key:generate

    - name: Run Database Migrations
      working-directory: backend/lumen
      run: php artisan migrate --force
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: test_db
        DB_USERNAME: root
        DB_PASSWORD: password

    - name: Execute tests via PHPUnit
      working-directory: backend/lumen
      run: vendor/bin/phpunit --coverage-text
