name: Node.js Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/node/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/node/**'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/node/package-lock.json

    - name: Install dependencies
      working-directory: backend/node
      run: npm ci

    - name: Run linter
      working-directory: backend/node
      run: npm run lint

    - name: Run tests
      working-directory: backend/node
      run: npm test
      env:
        REDIS_HOST: localhost
        REDIS_PORT: 6379

    - name: Build TypeScript
      working-directory: backend/node
      run: npm run build
